// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsXsj7J6zIGGlx3TA_5vbvwrNwE823t7A',
    appId: '1:376656909722:web:766ea2c806d744e2dbd623',
    messagingSenderId: '376656909722',
    projectId: 'fir-signin-ex',
    authDomain: 'fir-signin-ex.firebaseapp.com',
    storageBucket: 'fir-signin-ex.appspot.com',
    measurementId: 'G-QFZ0R2Y8BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuXUXRrKk9Ub6tUwhMR3XriDeIBOv9mDE',
    appId: '1:376656909722:android:b50bcf73079f7005dbd623',
    messagingSenderId: '376656909722',
    projectId: 'fir-signin-ex',
    storageBucket: 'fir-signin-ex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3SeEknU3V8BDc3X8R-fG9R8cDsgpEQeM',
    appId: '1:376656909722:ios:9e272ffde438857adbd623',
    messagingSenderId: '376656909722',
    projectId: 'fir-signin-ex',
    storageBucket: 'fir-signin-ex.appspot.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3SeEknU3V8BDc3X8R-fG9R8cDsgpEQeM',
    appId: '1:376656909722:ios:2164b5e070450ea2dbd623',
    messagingSenderId: '376656909722',
    projectId: 'fir-signin-ex',
    storageBucket: 'fir-signin-ex.appspot.com',
    iosBundleId: 'com.example.firebaseAuthen.RunnerTests',
  );
}
